version: "1"
services:

  caddy:
    depends_on:
      - wordpress
    # build: ./caddy_customization
    image: caddy:2.6.3-alpine
    container_name: caddyserver
    ports:
      - 8000:80
      - 4443:443
    volumes:
      - wordpress_data:/var/www/html
      - ./static_sites:/var/www/static_sites
      - $PWD/conf/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - wp-network

  db:
    env_file: 
      - ./config.env
    container_name: db
    image: mariadb:10.6.4-focal
    # expose:
    #   - 3306
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" 
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - wp-network

  wordpress:
    depends_on:
      - db
    env_file:
      - config.env
    build: ./wp_customization
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - "./conf/php.ini:$PHP_INI_DIR/conf.d/custom.ini"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    networks:
      - wp-network

  wp-cli:
    container_name: wp-cli
    image: wordpress:cli
    depends_on:
      - wordpress
    env_file:
      - config.env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp-network

volumes:
  caddy_data:
    external: true
  caddy_config:
  db_data:
  wordpress_data:

networks:
  wp-network:
    driver: bridge
